[package]
name = "dmg-cracker"
version = "0.1.3"
edition = "2021"
authors = ["James Davis <jamesecd@gmail.com"]
rust-version = "1.67.0"
description = "Tool for performing dictionary attacks on encrypted DMG images on OSX"
readme = "README.md"
homepage = "https://github.com/james-ecd/dmg-cracker"
respository = "https://github.com/james-ecd/dmg-cracker"
license-file = "LICENSE"
keywords = ["encrpyted", "dmg", "dictionary", "attack", "cracker"]
categories = ["command-line-utilities"]
exclude = ["/test_resources"]

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
console = "0.15.5"
indicatif = {version = "0.17.3", features = ["rayon"]}
num_cpus = "1.15.0"
random-string = "1.0.0"
rayon = "1.7.0"

[dev-dependencies]
mockall = "0.11.4"
regex = "1.7.3"
tempfile = "3.5.0"

[lib]
name = "dmg_cracker"
path = "src/lib.rs"

[[bin]]
name = "dmg-cracker"
path = "src/main.rs"
