name: Rust Tests and Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Run linting
      run: |
        cargo fmt --all -- --check
        cargo clippy --all-targets --all-features -- -D warnings

    - name: Install tarpaulin
      run: |
        cargo install cargo-tarpaulin

    - name: Run tests and collect coverage reports
      run: |
        cargo tarpaulin --out Xml
        mv target/tarpaulin.xml codecov.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}